// glossaryファイル English_conversation_R
`use strict`
const glossary = [
{target:`こんにちは。`, content:`Hello. `},
{target:`やあ。`, content:`Hi. `},
{target:`おはようございます。`, content:`Good morning. `},
{target:`こんにちは。`, content:`Good afternoon. `},
{target:`こんばんは。`, content:`Good evening. `},
{target:`お元気ですか？`, content:`How are you? `},
{target:`元気です、ありがとう。`, content:`I'm fine, thank you. `},
{target:`あなたの名前は何ですか？`, content:`What's your name? `},
{target:`私の名前は［あなたの名前］です。`, content:`My name is [Your Name]. `},
{target:`お会いできて嬉しいです。`, content:`Nice to meet you. `},
{target:`さようなら。`, content:`Goodbye. `},
{target:`またね。`, content:`See you later. `},
{target:`どうぞ。`, content:`Please. `},
{target:`ありがとう。`, content:`Thank you. `},
{target:`どういたしまして。`, content:`You're welcome. `},
{target:`すみません。`, content:`Excuse me. `},
{target:`ごめんなさい。`, content:`I'm sorry. `},
{target:`問題ありません。`, content:`No problem. `},
{target:`はい。`, content:`Yes. `},
{target:`いいえ。`, content:`No. `},
{target:`たぶん。`, content:`Maybe. `},
{target:`わかりません。`, content:`I don't know. `},
{target:`助けてもらえますか？`, content:`Can you help me? `},
{target:`もちろん。`, content:`Of course. `},
{target:`道に迷いました。`, content:`I'm lost. `},
{target:`トイレはどこですか？`, content:`Where is the bathroom? `},
{target:`これはいくらですか？`, content:`How much does this cost? `},
{target:`今何時ですか？`, content:`What time is it? `},
{target:`英語を話せますか？`, content:`Do you speak English? `},
{target:`わかりません。`, content:`I don't understand. `},
{target:`もう一度言っていただけますか？`, content:`Can you repeat that, please? `},
{target:`仕事は何をしていますか？`, content:`What do you do? `},
{target:`出身はどちらですか？`, content:`Where are you from? `},
{target:`ここにどれくらいいましたか？`, content:`How long have you been here? `},
{target:`今日の天気はどうですか？`, content:`What's the weather like today? `},
{target:`暑い／寒いです。`, content:`It's hot/cold. `},
{target:`［何か］が好きです。`, content:`I like [something]. `},
{target:`［何か］が嫌いです。`, content:`I don't like [something]. `},
{target:`趣味は何ですか？`, content:`What are your hobbies? `},
{target:`［アクティビティ］が大好きです。`, content:`I love to [activity]. `},
{target:`［アクティビティ］を楽しんでいます。`, content:`I enjoy [activity]. `},
{target:`今日はどうでしたか？`, content:`How was your day? `},
{target:`良かった／悪かったです。`, content:`It was good/bad. `},
{target:`週末の予定は何ですか？`, content:`What are your plans for the weekend? `},
{target:`［場所／アクティビティ］に行くつもりです。`, content:`I'm going to [place/activity]. `},
{target:`お会計お願いします。`, content:`Can I have the bill, please? `},
{target:`何がおすすめですか？`, content:`What do you recommend? `},
{target:`［料理］をください。`, content:`I'll have [dish]. `},
{target:`コーヒーをもらえますか？`, content:`Can I get a coffee, please? `},
{target:`それはどう綴りますか？`, content:`How do you spell that? `},
{target:`電話番号は何ですか？`, content:`What's your phone number? `},
{target:`どこに住んでいますか？`, content:`Where do you live? `},
{target:`［市／国］に住んでいます。`, content:`I live in [city/country]. `},
{target:`お気に入りの映画／本は何ですか？`, content:`What's your favorite movie/book? `},
{target:`写真を撮ってもいいですか？`, content:`Can I take a photo? `},
{target:`［場所］へはどう行けばいいですか？`, content:`How do I get to [place]? `},
{target:`医者が必要です。`, content:`I need a doctor. `},
{target:`最寄りの薬局はどこですか？`, content:`Where is the nearest pharmacy? `},
{target:`お誕生日おめでとうございます！`, content:`Happy birthday! `},
{target:`おめでとうございます！`, content:`Congratulations! `},
{target:`それを聞いてとても残念です。`, content:`I'm so sorry to hear that. `},
{target:`最近どう？`, content:`What's new? `},
{target:`それは面白いね。`, content:`That's interesting. `},
{target:`ペンを借りてもいいですか？`, content:`Can I borrow a pen? `},
{target:`今夜の予定はありますか？`, content:`Do you have any plans for tonight? `},
{target:`どこで英語を学びましたか？`, content:`Where did you learn English? `},
{target:`［何か］を探しています。`, content:`I'm looking for [something]. `},
{target:`おいしいレストランをお勧めできますか？`, content:`Can you recommend a good restaurant? `},
{target:`道に迷いました。道案内してくれますか？`, content:`I'm lost. Can you help me find my way? `},
{target:`そこへの一番良い行き方は何ですか？`, content:`What's the best way to get there? `},
{target:`いい天気ですね。`, content:`It's a beautiful day, isn't it? `},
{target:`［トピック］についてどう思いますか？`, content:`What do you think about [topic]? `},
{target:`よくわかりません。`, content:`I'm not sure. `},
{target:`もう少しゆっくり話していただけますか？`, content:`Can you speak more slowly, please? `},
{target:`［単語］の意味は何ですか？`, content:`What's the meaning of [word]? `},
{target:`説明が理解できません。`, content:`I don't understand the instructions. `},
{target:`もう一度説明していただけますか？`, content:`Could you please explain that again? `},
{target:`質問があります。`, content:`I have a question. `},
{target:`何か質問してもいいですか？`, content:`Can I ask you something? `},
{target:`このプロジェクトの締め切りはいつですか？`, content:`What's the deadline for this project? `},
{target:`明日休みをもらえますか？`, content:`Can I have a day off tomorrow? `},
{target:`遅れています。`, content:`I'm running late. `},
{target:`週末はどうでしたか？`, content:`How was your weekend? `},
{target:`お気に入りの音楽のジャンルは何ですか？`, content:`What's your favorite type of music? `},
{target:`頭痛がします。`, content:`I have a headache. `},
{target:`水をもらえますか？`, content:`Can I have some water, please? `},
{target:`新しい言語を学ぶ一番良い方法は何ですか？`, content:`What's the best way to learn a new language? `},
{target:`ホテルを探しています。`, content:`I'm looking for a hotel. `},
{target:`入場料はいくらですか？`, content:`How much is the entrance fee? `},
{target:`お気に入りの季節は何ですか？`, content:`What's your favorite season? `},
{target:`兄弟姉妹はいますか？`, content:`Do you have any siblings? `},
{target:`週末はどのように過ごしますか？`, content:`How do you spend your weekends? `},
{target:`旅行が大好きです。`, content:`I love to travel. `},
{target:`訪れたことのある場所で一番良かったところはどこですか？`, content:`What's the best place you've ever visited? `},
{target:`私はベジタリアンです。`, content:`I'm a vegetarian. `},
{target:`お勘定をお願いします。`, content:`Can I have the check, please? `},
{target:`生計を立てるために何をしていますか？`, content:`What do you do for a living? `},
{target:`おすすめの本を教えてもらえますか？`, content:`Can you recommend a good book? `},
{target:`この会話をとても楽しんでいます。`, content:`I'm really enjoying our conversation. `},
{target:`頑張ってね。`, content:`Break a leg. `},
{target:`我慢する、困難に立ち向かう。`, content:`Bite the bullet. `},
{target:`夜遅くまで働く。`, content:`Burn the midnight oil. `},
{target:`非常に高価である。`, content:`Cost an arm and a leg. `},
{target:`簡単なこと。`, content:`Piece of cake. `},
{target:`要点をつく、正確な指摘をする。`, content:`Hit the nail on the head. `},
{target:`大雨が降っている。`, content:`It's raining cats and dogs. `},
{target:`流行に乗る、他にもやる人がいるからやる。`, content:`Jump on the bandwagon. `},
{target:`秘密を漏らす。`, content:`Let the cat out of the bag. `},
{target:`とても簡単なこと。`, content:`A piece of cake. `},
{target:`突然に。`, content:`Out of the blue. `},
{target:`元気がない、体調が悪い。`, content:`Under the weather. `},
{target:`亡くなる。`, content:`Kick the bucket. `},
{target:`関係を断つ。`, content:`Burn bridges. `},
{target:`仲直りする。`, content:`Bury the hatchet. `},
{target:`緊張している。`, content:`Butterflies in my stomach. `},
{target:`叶わなかったことを嘆く。`, content:`Cry over spilled milk. `},
{target:`蓋を開ける前に先走るな。`, content:`Don't count your chickens before they hatch. `},
{target:`非常に簡単。`, content:`Easy as pie. `},
{target:`どんな困難にも良い面がある。`, content:`Every cloud has a silver lining. `},
{target:`言葉よりも画像の方が意味がある。`, content:`A picture is worth a thousand words. `},
{target:`責任をとる。`, content:`Face the music. `},
{target:`寝る。`, content:`Hit the hay. `},
{target:`問題や課題は双方にある。`, content:`It takes two to tango. `},
{target:`流行に乗る。`, content:`Jumping on the bandwagon. `},
{target:`注意を払う。`, content:`Keep an eye on the ball. `},
{target:`問題を起こさないようにする。`, content:`Let sleeping dogs lie. `},
{target:`チャンスを逃す。`, content:`Miss the boat. `},
{target:`苦労なくして成功なし。`, content:`No pain, no gain. `},
{target:`責任が免れる。`, content:`Off the hook. `},
{target:`楽しい時間を過ごす。`, content:`Paint the town red. `},
{target:`リスクを取る。`, content:`Put all your eggs in one basket. `},
{target:`決断はあなた次第。`, content:`The ball is in your court. `},
{target:`困難な時でも支え合う。`, content:`Through thick and thin. `},
{target:`何を考えているか教えて。`, content:`A penny for your thoughts. `},
{target:`興味津々。`, content:`All ears. `},
{target:`誤った方向に取り組む。`, content:`Barking up the wrong tree. `},
{target:`徹夜で働く。`, content:`Burn the midnight oil. `},
{target:`叶わなかったことを嘆く。`, content:`Cry over spilled milk. `},
{target:`要点を述べる。`, content:`Cut to the chase. `},
{target:`リスクを分散する。`, content:`Don't put all your eggs in one basket. `},
{target:`非常に簡単。`, content:`Easy as pie. `},
{target:`とても健康。`, content:`Fit as a fiddle. `},
{target:`臆病になる。`, content:`Get cold feet. `},
{target:`寝る。`, content:`Hit the hay. `},
{target:`流行に乗る。`, content:`Jump on the bandwagon. `},
{target:`注意を払う。`, content:`Keep an eye on the ball. `},
{target:`秘密を漏らす。`, content:`Let the cat out of the bag. `},
{target:`手短に話す。`, content:`Make a long story short. `},
{target:`苦労なくして成功なし。`, content:`No pain, no gain. `},
{target:`責任が免れる。`, content:`Off the hook. `},
{target:`代償を支払う。`, content:`Pay the piper. `},
{target:`簡単なこと。`, content:`Piece of cake. `},
{target:`一度にやめる。`, content:`Quit cold turkey. `},
{target:`経験則。`, content:`Rule of thumb. `},
{target:`決断はあなた次第。`, content:`The ball is in your court. `},
{target:`元気がない、体調が悪い。`, content:`Under the weather. `},
{target:`夜遅くまで働く。`, content:`Burn the midnight oil. `},
{target:`困難に立ち向かう。`, content:`Bite the bullet. `},
{target:`ごくありふれたもの。`, content:`A dime a dozen. `},
{target:`興味津々。`, content:`All ears. `},
{target:`積極的なやり取りを始める。`, content:`Break the ice. `},
{target:`叶わなかったことを嘆く。`, content:`Cry over spilled milk. `},
{target:`要点を述べる。`, content:`Cut to the chase. `},
{target:`リスクを分散する。`, content:`Don't put all your eggs in one basket. `},
{target:`どんな困難にも良い面がある。`, content:`Every cloud has a silver lining. `},
{target:`責任をとる。`, content:`Face the music. `},
{target:`臆病になる。`, content:`Get cold feet. `},
{target:`要点をつく、正確な指摘をする。`, content:`Hit the nail on the head. `},
{target:`大雨が降っている。`, content:`It's raining cats and dogs. `},
{target:`流行に乗る。`, content:`Jump on the bandwagon. `},
{target:`注意を払う。`, content:`Keep an eye on the ball. `},
{target:`秘密を漏らす。`, content:`Let the cat out of the bag. `},
{target:`手短に話す。`, content:`Make a long story short. `},
{target:`苦労なくして成功なし。`, content:`No pain, no gain. `},
{target:`責任が免れる。`, content:`Off the hook. `},
{target:`代償を支払う。`, content:`Pay the piper. `},
{target:`簡単なこと。`, content:`Piece of cake. `},
{target:`一度にやめる。`, content:`Quit cold turkey. `},
{target:`経験則。`, content:`Rule of thumb. `},
{target:`決断はあなた次第。`, content:`The ball is in your court. `},
{target:`元気がない、体調が悪い。`, content:`Under the weather. `},
{target:`夜遅くまで働く。`, content:`Burn the midnight oil. `},
{target:`困難に立ち向かう。`, content:`Bite the bullet. `},
{target:`ごくありふれたもの。`, content:`A dime a dozen. `},
{target:`興味津々。`, content:`All ears. `},
{target:`積極的なやり取りを始める。`, content:`Break the ice. `},
{target:`叶わなかったことを嘆く。`, content:`Cry over spilled milk. `},
{target:`要点を述べる。`, content:`Cut to the chase. `},
{target:`リスクを分散する。`, content:`Don't put all your eggs in one basket. `},
{target:`どんな困難にも良い面がある。`, content:`Every cloud has a silver lining. `},
{target:`責任をとる。`, content:`Face the music. `},
{target:`臆病になる。`, content:`Get cold feet. `},
{target:`要点をつく、正確な指摘をする。`, content:`Hit the nail on the head. `},
{target:`大雨が降っている。`, content:`It's raining cats and dogs. `},
{target:`流行に乗る。`, content:`Jump on the bandwagon. `},
{target:`注意を払う。`, content:`Keep an eye on the ball. `},
{target:`秘密を漏らす。`, content:`Let the cat out of the bag. `},
{target:`手短に話す。`, content:`Make a long story short. `},
{target:`苦労なくして成功なし。`, content:`No pain, no gain. `},
{target:`まっすぐ進んでください。`, content:`Go straight ahead.`},
{target:`次の交差点で左に曲がってください。`, content:`Turn left at the next intersection.`},
{target:`信号を過ぎて右に曲がってください。`, content:`Turn right after the traffic light.`},
{target:`すぐ角を曲がったところです。`, content:`It's just around the corner.`},
{target:`近づいていますね。`, content:`You're getting close.`},
{target:`左に2本目の道を取ってください。`, content:`Take the second street on the left.`},
{target:`右側にあります。`, content:`It's on your right-hand side.`},
{target:`橋を渡ってから左に曲がってください。`, content:`Cross the bridge and then turn left.`},
{target:`[場所] の案内に従ってください。`, content:`Follow the signs for [place].`},
{target:`右側に公園があります。`, content:`You'll pass a park on your right.`},
{target:`約10分間まっすぐ歩いてください。`, content:`Walk straight for about 10 minutes.`},
{target:`ここから歩いてすぐです。`, content:`It's a short walk from here.`},
{target:`エレベーターで3階に行ってください。`, content:`Take the elevator to the third floor.`},
{target:`バス停は図書館の前にあります。`, content:`The bus stop is in front of the library.`},
{target:`市街地の方向に進んでください。`, content:`Head towards the city center.`},
{target:`博物館は道路の反対側にあります。`, content:`The museum is on the opposite side of the street.`},
{target:`高い建物なので見逃すことはありません。`, content:`You can't miss it; it's the tall building.`},
{target:`路地を抜けて左側に見つかります。`, content:`Go through the alley, and you'll find it on the left.`},
{target:`ここから車で15分です。`, content:`It's a 15-minute drive from here.`},
{target:`大きな赤い看板が見えるまで進んでください。`, content:`Keep going until you see a big red sign.`},
{target:`すぐに目的地に到着します。`, content:`You'll reach your destination in no time.`},
{target:`道路の曲線に従ってください。`, content:`Follow the curve of the road.`},
{target:`町の外れにあります。`, content:`It's on the outskirts of town.`},
{target:`[方向] 行きの地下鉄に乗ってください。`, content:`Take the subway going in the direction of [direction].`},
{target:`少し遠いですが、眺めは価値があります。`, content:`It's a bit of a hike, but the view is worth it.`},
{target:`正しい方向です。そのまま進んでください。`, content:`You're on the right track; keep going.`},
{target:`道の名前は少し混乱するかもしれませんが、心配しないでください。`, content:`The street names can be a bit confusing, but don't worry.`},
{target:`次の交差点でＵターンしてください。`, content:`You'll need to make a U-turn at the next intersection.`},
{target:`ショッピングエリアの中心部にあります。`, content:`It's in the heart of the shopping district.`},
{target:`駅に到達したら、行き過ぎています。`, content:`If you reach the train station, you've gone too far.`},
{target:`これはいくらですか？`, content:`How much is this?`},
{target:`この商品には割引がありますか？`, content:`Is there a discount on this item?`},
{target:`領収書をもらえますか？`, content:`Can I get a receipt, please?`},
{target:`クレジットカードは使えますか？`, content:`Do you accept credit cards?`},
{target:`セールは行われていますか？`, content:`Is there a sale going on?`},
{target:`[商品] はどこで見つかりますか？`, content:`Where can I find [product]?`},
{target:`返品ポリシーは何ですか？`, content:`What's the return policy?`},
{target:`他に追加の料金はありますか？`, content:`Are there any additional fees?`},
{target:`これを試着してもいいですか？`, content:`Can I try this on?`},
{target:`今日は何かキャンペーンがありますか？`, content:`Are there any promotions today?`},
{target:`これは他の色／サイズでもありますか？`, content:`Do you have this in a different color/size?`},
{target:`試着室はどこですか？`, content:`Where is the fitting room?`},
{target:`[特定のブランド] を探すのを手伝ってもらえますか？`, content:`Can you help me find [specific brand]?`},
{target:`この商品には保証がついていますか？`, content:`Is there a warranty on this product?`},
{target:`複数購入すると割引がありますか？`, content:`Can I get a discount if I buy more than one?`},
{target:`ギフト包装はありますか？`, content:`Do you offer gift wrapping?`},
{target:`どの支払い方法を受け付けていますか？`, content:`What forms of payment do you accept?`},
{target:`ロイヤリティプログラムはありますか？`, content:`Is there a loyalty program?`},
{target:`私をサポートしてくれるセールスマンはいますか？`, content:`Are there any salespeople available to assist me?`},
{target:`これらのアイテムに袋をもらえますか？`, content:`Can I get a bag for these items?`},
{target:`保証期間はどれくらいですか？`, content:`How long is the warranty valid?`},
{target:`会員向けの特別なオファーはありますか？`, content:`Are there any special offers for members?`},
{target:`現金払いの割引はありますか？`, content:`Is there a cash discount?`},
{target:`消費税がかかりますか？`, content:`Are there any sales tax charges?`},
{target:`サイズが合わない場合、これは返品できますか？`, content:`Can I return this if it doesn't fit?`},
{target:`分割払いの選択肢はありますか？`, content:`Are there any installment payment options?`},
{target:`似たような商品をお勧めしてもらえますか？`, content:`Can you recommend similar products?`},
{target:`これは最新のモデル／バージョンですか？`, content:`Is this the latest model/version?`},
{target:`お客様向けの忠誠度プログラムはありますか？`, content:`Do you have a customer loyalty program?`},
{target:`思い直した場合、返金は可能ですか？`, content:`Can I get a refund if I change my mind?`},
{target:`1泊の宿泊料金はいくらですか？`, content:`What's the room rate per night?`},
{target:`朝食は宿泊料金に含まれていますか？`, content:`Is breakfast included in the room rate?`},
{target:`眺めの良い部屋をお願いできますか？`, content:`Can I have a room with a view?`},
{target:`チェックイン／チェックアウトは何時ですか？`, content:`What time is check-in/check-out?`},
{target:`起床のお知らせをお願いできますか？`, content:`Can I get a wake-up call?`},
{target:`部屋で無料のWi-Fiはありますか？`, content:`Is there free Wi-Fi in the rooms?`},
{target:`駐車場はありますか？`, content:`Do you have parking available?`},
{target:`クレジットカードで支払えますか？`, content:`Can I pay with a credit card?`},
{target:`空港へのシャトルサービスはありますか？`, content:`Is there a shuttle service to the airport?`},
{target:`ペットはホテル内に入れますか？`, content:`Are pets allowed in the hotel?`},
{target:`禁煙の部屋をリクエストできますか？`, content:`Can I request a non-smoking room?`},
{target:`ホテルは［名所］からどれくらいの距離ですか？`, content:`How far is the hotel from [landmark]?`},
{target:`他に追加の料金や税金はありますか？`, content:`Are there any additional fees or taxes?`},
{target:`チェックイン前やチェックアウト後に荷物を預けることはできますか？`, content:`Can I store my luggage before check-in or after check-out?`},
{target:`ホテル内にはジムやフィットネスセンターがありますか？`, content:`Is there a gym or fitness center in the hotel?`},
{target:`部屋にはどのような設備が含まれていますか？`, content:`What amenities are included in the room?`},
{target:`タオルやアメニティを追加してもらえますか？`, content:`Can I have extra towels/toiletries?`},
{target:`24時間ルームサービスは利用可能ですか？`, content:`Is room service available 24/7?`},
{target:`おすすめの地元のレストランはありますか？`, content:`Can you recommend any good local restaurants?`},
{target:`ホテルのWi-Fiに接続する方法は？`, content:`How do I connect to the hotel's Wi-Fi?`},
{target:`宿泊を追加できますか？`, content:`Can I extend my stay for an extra night?`},
{target:`ホテルにはプールやスパがありますか？`, content:`Is there a pool or spa in the hotel?`},
{target:`予約のキャンセルや変更は可能ですか？`, content:`Can I cancel or modify my reservation?`},
{target:`朝食は無料で提供されますか？`, content:`Do you provide a complimentary breakfast?`},
{target:`ホテルのキャンセルポリシーは何ですか？`, content:`What is the hotel's cancellation policy?`},
{target:`レイトチェックアウトをリクエストできますか？`, content:`Can I request a late check-out?`},
{target:`ビジネスセンターと印刷サービスはありますか？`, content:`Is there a business center with printing services?`},
{target:`近くの観光スポットや見所をお勧めしてもらえますか？`, content:`Can you recommend any nearby attractions or sightseeing spots?`},
{target:`ホテルにはバーまたはラウンジがありますか？`, content:`Is there a bar or lounge in the hotel?`},
{target:`[目的地] への移動手段を手配してもらえますか？`, content:`Can you arrange transportation for me to [destination]?`},
{target:`メニューを見せていただけますか？`, content:`May I see the menu, please? `},
{target:`今日のおすすめは何ですか？`, content:`What's the special of the day? `},
{target:`シェフのおすすめをお願いします。`, content:`I'll have the chef's special. `},
{target:`二人用のテーブルをお願いできますか？`, content:`Can I get a table for two? `},
{target:`この席は埋まっていますか？`, content:`Is this seat taken? `},
{target:`予約をしたいのですが。`, content:`I'd like to make a reservation. `},
{target:`今日のスープは何ですか？`, content:`What's the soup of the day? `},
{target:`注文をします。`, content:`I'm ready to order. `},
{target:`水を一杯お願いします。`, content:`Can I have a glass of water, please? `},
{target:`私はナッツアレルギーがあります。`, content:`I'm allergic to nuts. `},
{target:`この料理はどれくらい辛いですか？`, content:`How spicy is this dish? `},
{target:`フライをサラダに変えてもらえますか？`, content:`Can I substitute the fries for a salad? `},
{target:`デザートは何がおすすめですか？`, content:`What do you recommend for dessert? `},
{target:`サービス料は含まれていますか？`, content:`Is service charge included? `},
{target:`お会計をお願いします。`, content:`Could we have the check, please? `},
{target:`料理はおいしかったですね！`, content:`The food was delicious! `},
{target:`これは私の味には少ししょっぱすぎます。`, content:`This is too salty for my taste. `},
{target:`別々にお会計します。`, content:`I'll take the bill separately. `},
{target:`ご注文はお決まりですか？`, content:`Are you ready to order? `},
{target:`すみません、もっとナプキンをください。`, content:`Excuse me, we need more napkins. `},
{target:`チップは請求書に含まれていますか？`, content:`Is the tip included in the bill? `},
{target:`残り物を持ち帰りできますか？`, content:`Can I have a doggy bag for the leftovers? `},
{target:`テーブルの待ち時間はどれくらいですか？`, content:`How long is the wait for a table? `},
{target:`お会計をお願いします。`, content:`The check, please. `},
{target:`お店の特別メニューは何ですか？`, content:`What's the house specialty? `},
{target:`請求書を分けてもらえますか？`, content:`Is it possible to split the bill? `},
{target:`ドレッシングは別にしてもらえますか？`, content:`Can I have the dressing on the side? `},
{target:`ここのサービスは素晴らしいですね。`, content:`The service here is excellent. `},
{target:`ベジタリアン向けのオプションはありますか？`, content:`Is there a vegetarian option? `},
{target:`これは少し焼きすぎです。`, content:`This is a bit overcooked. `},
{target:`ステーキはミディアムレアでお願いします。`, content:`I'd like my steak medium rare. `},
{target:`もっとパンをください。`, content:`Could I have some more bread, please? `},
{target:`子供向けのメニューはありますか？`, content:`Is there a kids' menu available? `},
{target:`今日の日替わりメニューにします。`, content:`I'll go with the daily special. `},
{target:`キャンセル料はいくらですか？`, content:`How much is the corkage fee? `},
{target:`この料理は少し味気ないです。`, content:`This dish is a bit too bland. `},
{target:`ワインのおすすめはありますか？`, content:`Do you have any recommendations for wine? `},
{target:`もう一杯おかわりできますか？`, content:`Could I have a refill, please? `},
{target:`今、デザートを注文します。`, content:`I'd like to order dessert now. `},
{target:`チップは請求書に含まれていますか？`, content:`Is the gratuity included in the bill? `},
{target:`この料理は私には辛すぎます。`, content:`This dish is too spicy for me. `},
{target:`デザートのメニューを見せていただけますか？`, content:`Could we have the dessert menu? `},
{target:`彼/彼女と同じものをください。`, content:`I'll have the same as her/him. `},
{target:`この料理には満足していません。`, content:`I'm not satisfied with this dish. `},
{target:`この魚はどのように調理されていますか？`, content:`How is the fish cooked? `},
{target:`ポーションが小さすぎます。`, content:`The portion size is too small. `},
{target:`もっと氷をください。`, content:`Can I get some more ice, please? `},
{target:`料理のプレゼンテーションが素晴らしいです。`, content:`The food presentation is impressive. `},
{target:`コーヒーはブラックでお願いします。`, content:`I'll have my coffee black. `},
{target:`お店の特別メニューはありますか？`, content:`Are there any house specialties? `},
{target:`ねえ！最近どうだった？`, content:`Hey! How have you been?`},
{target:`最近何か新しいことあった？`, content:`What's new with you?`},
{target:`コーヒーでも飲みながら近況を話そうよ。`, content:`Let's catch up over coffee.`},
{target:`旅行に行ったって聞いたよ。どうだったの？`, content:`I heard you went on a trip. How was it?`},
{target:`今週末一緒に遊びに行かない？`, content:`Do you want to hang out this weekend?`},
{target:`昨晩、すごい映画を見たんだ。`, content:`I watched this amazing movie last night.`},
{target:`最近できたダウンタウンの新しいレストラン行ったことある？`, content:`Have you tried that new restaurant downtown?`},
{target:`最後に会ったのがこんなに長い間前だなんて信じられない。`, content:`I can't believe it's been so long since we last met.`},
{target:`今夜は何かしたいことある？`, content:`What do you feel like doing tonight?`},
{target:`[ニュース／イベント] 聞いたことある？`, content:`Did you hear about [news/event]?`},
{target:`うちで映画の夜を計画しようよ。`, content:`Let's plan a movie night at my place.`},
{target:`分かち合いたい興奮するようなニュースがあるんだ！`, content:`I have some exciting news to share!`},
{target:`最近の仕事、どうなの？`, content:`How's work going for you lately?`},
{target:`今日、なんと起こったか当ててみて！`, content:`Guess what happened to me today!`},
{target:`絶対に一緒に旅行に行かなきゃね。`, content:`We should definitely go on a trip together sometime.`},
{target:`新しい趣味始めたんだ。すごく楽しいよ！`, content:`I started a new hobby. It's so much fun!`},
{target:`良い本あれば教えてくれない？`, content:`Can you recommend any good books to read?`},
{target:`ちょっとアドバイスが欲しいんだけど。`, content:`I need your advice on something.`},
{target:`明日ランチ一緒に行かない？`, content:`Do you want to join me for lunch tomorrow?`},
{target:`この新しい曲がやめられないんだ。聞いてみるべきだよ！`, content:`I can't stop listening to this new song. You should check it out!`},
{target:`仲間とゲームの夜を計画しよう。`, content:`Let's plan a game night with the gang.`},
{target:`部屋をリフォームしようと思ってるんだ。アイデアある？`, content:`I'm thinking of redecorating my place. Any ideas?`},
{target:`送った面白いミーム見た？`, content:`Did you see that hilarious meme I sent you?`},
{target:`来週のコンサートが楽しみでたまらない。`, content:`I'm so excited about the upcoming concert.`},
{target:`今週末ビーチデーを計画しよう。`, content:`Let's plan a beach day this weekend.`},
{target:`もう夏も終わりか。時が経つのは早いね！`, content:`I can't believe summer is almost over. Time flies!`},
{target:`家族は元気？`, content:`How's your family doing?`},
{target:`みんなが話題にしてる新しいカフェ試してみない？`, content:`We should try that new cafe everyone's talking about.`},
{target:`笑いが必要だ。今夜はコメディを見よう。`, content:`I need a good laugh. Let's watch a comedy tonight.`},
{target:`いつもそばにいてくれてありがとう。最高だよ！`, content:`Thanks for always being there for me. You're the best!`},
{target:`おはようございます！今日はいかがですか？`, content:`Good morning! How are you today?`},
{target:`週末は良かったですか？`, content:`I hope you had a good weekend.`},
{target:`今日のミーティングの議題を渡していただけますか？`, content:`Could you please pass me the agenda for today's meeting?`},
{target:`新しいプロジェクトについて少し話す時間はありますか？`, content:`Do you have a moment to discuss the new project?`},
{target:`四半期の成績を確認するためにチームミーティングを予定しましょう。`, content:`Let's schedule a team meeting to go over the quarterly results.`},
{target:`ブレーンストーミングセッションでのご意見、ありがとうございます。`, content:`I appreciate your input during the brainstorming session.`},
{target:`現在進行中のタスクについてアップデートしていただけますか？`, content:`Can you provide an update on your current tasks?`},
{target:`締切を守る必要があります。タスクの優先順位をつけましょう。`, content:`We need to meet our deadlines. Let's prioritize tasks.`},
{target:`今日中にレポートを送ります。`, content:`I'll send you the report by the end of the day.`},
{target:`クライアントのプロジェクトの進捗はどうですか？`, content:`How's the progress on the client project?`},
{target:`マーケティングキャンペーンの新しい戦略を提案したいと思います。`, content:`I'd like to propose a new strategy for the marketing campaign.`},
{target:`目標について話すために1対1のミーティングを予定できますか？`, content:`Can we schedule a one-on-one meeting to discuss your goals?`},
{target:`大きな問題になる前にこの問題に対処する必要があります。`, content:`We need to address the issue before it becomes a bigger problem.`},
{target:`このプロジェクトでのご協力、感謝しています。`, content:`I appreciate your collaboration on this project.`},
{target:`リモートチームメンバーを含めた会議のセッティングをしましょう。`, content:`Let's set up a conference call to include our remote team members.`},
{target:`来るイベントのロジスティクスは私が担当します。`, content:`I'll handle the logistics for the upcoming event.`},
{target:`市場のトレンドについていくつかの洞察を教えていただけますか？`, content:`Can you provide some insights into the market trends?`},
{target:`チーム内でオープンなコミュニケーションを保つことは重要です。`, content:`It's essential to maintain open communication within the team.`},
{target:`この課題に対する解決策を見つけるために協力しましょう。`, content:`Let's collaborate to find a solution to this challenge.`},
{target:`レビュー用に関連する文書を転送します。`, content:`I'll forward you the relevant documents for your review.`},
{target:`新しいソフトウェアのトレーニングセッションを予定できます。`, content:`We can schedule a training session for the new software.`},
{target:`あなたのフィードバックはプロセスの改善に不可欠です。`, content:`Your feedback is crucial for the improvement of our processes.`},
{target:`クライアントに連絡して、彼らの懸念事項に対処することをお勧めします。`, content:`I recommend reaching out to the client to address their concerns.`},
{target:`来月、チームビルディングのアクティビティを企画しましょう。`, content:`Let's organize a team-building activity for next month.`},
{target:`このプロジェクトに関するあなたの期待を明確にしていただけますか？`, content:`Could you clarify your expectations regarding this project?`},
{target:`チームメンバーの頑張りを認めるべきです。`, content:`We should acknowledge the hard work of our team members.`},
{target:`詳細なプロジェクトのタイムラインを作成することを提案します。`, content:`I suggest creating a detailed project timeline.`},
{target:`最近の成功を祝うためにチームの外出を計画しましょう。`, content:`Let's plan a team outing to celebrate our recent successes.`},
{target:`来るクライアントプレゼンテーションのための書類は私が担当します。`, content:`I'll handle the paperwork for the upcoming client presentation.`},
{target:`ポジティブな職場環境を維持することが重要です。`, content:`It's important to maintain a positive work environment.`},
{target:`それについてはよくわからないんです。`, content:`I'm not sure about that.`},
{target:`今のところ未定です。`, content:`It's up in the air right now.`},
{target:`その場の流れで決めましょう。`, content:`Let's play it by ear.`},
{target:`事の進行具合を見ます。`, content:`I'll see how things go.`},
{target:`それは可能性があります。`, content:`That's a possibility.`},
{target:`検討してみるかもしれません。`, content:`I might consider it.`},
{target:`何が起こるか見てみましょう。`, content:`We'll see what happens.`},
{target:`現時点では少し不透明です。`, content:`It's a bit unclear at the moment.`},
{target:`まだ決めていません。`, content:`I haven't made up my mind yet.`},
{target:`考えてみます。`, content:`I'll think about it.`},
{target:`明確な答えがありません。`, content:`I don't have a definite answer.`},
{target:`まだ検討中です。`, content:`It's still under consideration.`},
{target:`提案にはオープンです。`, content:`I'm open to suggestions.`},
{target:`これは微妙な問題です。`, content:`It's a gray area.`},
{target:`どちらにするか迷っています。`, content:`I'm on the fence.`},
{target:`まだ何にも決めていません。`, content:`I haven't committed to anything yet.`},
{target:`ある程度曖昧さがあります。`, content:`There's some ambiguity.`},
{target:`完全に納得していません。`, content:`I'm not entirely convinced.`},
{target:`まだ議論の余地があります。`, content:`It's still up for debate.`},
{target:`結論を急ぎたくありません。`, content:`I don't want to jump to conclusions.`},
{target:`まだ確定していません。`, content:`It's not set in stone.`},
{target:`解釈の余地があります。`, content:`There's room for interpretation.`},
{target:`選択肢をオープンにしておきます。`, content:`I'll keep my options open.`},
{target:`完全には否定していません。`, content:`I haven't ruled it out completely.`},
{target:`これは少し微妙な問題です。`, content:`It's a bit of a gray area.`},
{target:`まだそれを解明していません。`, content:`I haven't figured it out yet.`},
{target:`流れに任せます。`, content:`I'll go with the flow.`},
{target:`片方に傾いていません。`, content:`I'm not leaning either way.`},
{target:`まだ探索段階です。`, content:`It's still in the exploration phase.`},
{target:`決断する前にもっと情報が必要です。`, content:`I need more information before deciding.`},
{target:`完全には明確ではありません。`, content:`It's not crystal clear.`},
{target:`結論を出さずにおきます。`, content:`I'm keeping it open-ended.`},
{target:`様子を見るスタンスです。`, content:`I'm taking a wait-and-see approach.`},
{target:`まだ決める段階に至っていません。`, content:`I haven't gotten around to deciding.`},
{target:`まだ感触を探っています。`, content:`I'm still feeling it out.`},
{target:`もっと時間がかかりそうです。`, content:`I'll need more time to think about it.`},
{target:`今は少し曖昧です。`, content:`It's a bit hazy right now.`},
{target:`しっかりとした決断はしていません。`, content:`I haven't made a firm decision.`},
{target:`選択肢を探っています。`, content:`I'm exploring my options.`},
{target:`決断の途中です。`, content:`I'm in the process of deciding.`},
{target:`それについて完全には理解していません。`, content:`I'm not entirely clear on that.`},
{target:`まだ考慮の段階にいます。`, content:`I'm still in the contemplation stage.`},
{target:`事の進行を見ます。`, content:`I'll see how things pan out.`},
{target:`利点と欠点を考えています。`, content:`I'm still weighing the pros and cons.`},
{target:`時が来たら決めます。`, content:`I'll decide when the time is right.`},
{target:`これは少し謎めいています。`, content:`It's a bit of a puzzle to me.`},
{target:`それはまだ解決できていません。`, content:`I haven't cracked that nut yet.`},
{target:`今のところ安全を確保しています。`, content:`I'm playing it safe for now.`},
{target:`それについてはまだ迷っています。`, content:`I'm still on the fence about it.`},
{target:`それを考え込む必要があります。`, content:`I'll need to mull it over.`},
]
